services:
  - type: web
    name: mongpt-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: "8735549741:AAFt4ydTV5BFGhVv_iKKJbO3TxfefbIpEc0"
      - key: POE_API_KEY
        value: "PKkByuEiScElrfyx7VGeztMX6xoDQv_O5p8G3Bwio_M"
